"""users

Revision ID: e4fdc2f27ee1
Revises: 9726095dede7
Create Date: 2021-12-15 14:12:21.142397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4fdc2f27ee1'
down_revision = '9726095dede7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('did', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_confidence'), 'user', ['confidence'], unique=False)
    op.create_index(op.f('ix_user_did'), 'user', ['did'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_rating'), 'user', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_rating'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_did'), table_name='user')
    op.drop_index(op.f('ix_user_confidence'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###